import { testProgram } from './_runTest';

testProgram('1 2 <', [true]);
testProgram('2 1 <', [false]);
testProgram('2 2 =', [true]);
testProgram('2 1 =', [false]);
testProgram('2 2 !=', [false]);
testProgram('2 1 !=', [true]);
testProgram('2 1 >=', [true]);
testProgram('1 2 >=', [false]);
testProgram('2 1 <=', [false]);
testProgram('1 2 <=', [true]);
testProgram('true false ||', [true]);
testProgram('false false ||', [false]);
testProgram('false true ||', [true]);
testProgram('true true ||', [true]);
testProgram('true false &&', [false]);
testProgram('false false &&', [false]);
testProgram('false true &&', [false]);
testProgram('true true &&', [true]);
testProgram('[] small', [true]);
testProgram('[1] small', [true]);
testProgram('[1 2] small', [false]);
testProgram('-2 small', [false]);
testProgram('-1 small', [true]);
testProgram('0 small', [true]);
testProgram('1 small', [true]);
testProgram('2 small', [false]);
testProgram('"0" small', [false]);
testProgram('"1" small', [false]);
testProgram('true small', [false]);
testProgram('false small', [false]);
testProgram('[] zero', [true]);
testProgram('[1] zero', [false]);
testProgram('-1 zero', [false]);
testProgram('0 zero', [true]);
testProgram('1 zero', [false]);
testProgram('"0" zero', [false]);
testProgram('"1" zero', [false]);
testProgram('true zero', [false]);
testProgram('false zero', [false]);
